sudo: false
language: node_js
node_js:
  - "7.0"

cache:
  directories:
    - node_modules
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - npm install
script:
  - npm run test-ci
  - npm run lint
after_success:
 # - npm run build
 # - firebase deploy --token ${FIREBASE_TOKEN}